### ISSUE TITLE
Show text in widgets instead of pages

### ISSUE THREAD

**Issue by ArchCarrier** [realbigplugins/client-dash#102]
It would be great if Client Dash had an option to show text inside the widget on the dashboard instead of on a separate page. Especially on higher resolutions the icons are huge and seem a waste of space. Most of the information could be shown inside the widget. The dashicons could be shown in the widget's title.

**Comment by joelworsham** [comment]
This is a great suggestion, and something we've definitely thought about in the past. I would expect to see something along these lines sometime in the future for sure.

**Comment by joelworsham** [comment]
Solved in 2.0 with text dashboard widget
