### ISSUE TITLE
User Created Webmaster-Like Pages

### ISSUE THREAD

**Issue by brandonecarr** [realbigplugins/client-dash#103]
Under the Webmaster tab, admins can have whatever information they want, and when the icon is clicked, the user is taken to another page. I think this functionality should be built out so that more than just 1 can be used. I know you're building in the option to create custom CD widgets with custom URL's, but if you could build in the option to create a new page in admin like the Webmaster widget does, that would be awesome. What our company primarily handles is medical marijuana dispensaries. I'd like to build in the functionality, just like I have with the "Open A Ticket", to "Update Your Menu". So, client would click on the CD Widget, and they would be taken to the admin page with the menu that they can add, remove, and edit any menu item they wish.

**Comment by brashrebel** [comment]
I really like the sound of this. I think that this would be relatively easy to create on an individual basis using the extension generator http://clientdash.io/generator/. As for an option in Client Dash, we'll likely be including soon a custom widget which could be linked to any existing URL. And regarding the creation of an additional admin page, I'm not certain that would be an appropriate function for Client Dash or not. I haven't considered it yet. How would you expect that to work?

**Comment by brandonecarr** [comment]
I imagine that this change would be a big one, but it seems like it would be a good one, IMO. I'll let you decide. From Settings>Client Dash, there is a "Webmaster" tab. Inside that tab contain all the elements to create a page for that CD widget (Webmaster Name, Tab Name and Content). My suggestion would be to replace this tab with a new tab that acts just like the native Pages tab in Wordpress does. Instead of creating pages, you'd be creating custom tab pages like you can on the Webmaster tab. I've created a little mockup to aide in my explanation:

First off, the Dashboard itself:

![mudashboard](https://cloud.githubusercontent.com/assets/5378673/6515570/d604da52-c33f-11e4-8759-debc81ec60c5.png)
The dashboard can be modified the same way from the widgets tab in the settings. 


![mupages](https://cloud.githubusercontent.com/assets/5378673/6515572/d606805a-c33f-11e4-880b-fe1533d0f2dc.png)
As you can see, I've replaced the Webmaster tab, with a Pages tab. This way, multiple custom widgets can be created. 


![munewpost](https://cloud.githubusercontent.com/assets/5378673/6515571/d60506bc-c33f-11e4-96b7-1661f8f55daa.png)
This is the Add New screen that the user will be directed to from the previous image. It requests the same information the old Webmaster tab did, but it also allows to select an icon. Maybe even allow the user to upload a custom icon. When you go into the custom widget on the dashboard, it seems to be setup for multiple tabs. So, I added the plus and minus buttons to add tabs into the custom widgets. 

Anyways, just a thought mocked up. What do you think?

**Comment by brashrebel** [comment]
I really really really really like this idea. I can see so much potential here. We'll be exploring this soon.

I love the thought that this familiar interface could be employed for registering and building new admin pages. This would also open the door for other cool things like possibly outputting the contents of the pages through `the_content` filter so that things like shortcodes would work within them. Just more thoughts. Again, thanks @brandonecarr for your ideas and the excellent mockup.

**Comment by brandonecarr** [comment]
@brashrebel Yes! Now you're exactly where I'm at! Being able to add shortcodes and html would be epic! The possibilities would literally be endless!! I look forward to the future of CD. I think big things are coming one way or the other. :) Thanks again for your hard work Kyle!

**Comment by joelworsham** [comment]
Solved via Pro version with admin pages/tabs
