### ISSUE TITLE
freeze on menus

### ISSUE THREAD

**Issue by Jy86422000** [realbigplugins/client-dash#109]
Site froze while adding a CD menu.  While creating I got to 93% and it stuck there for over ten minutes.  I finally refreshed despite the "please stay on this page" message and everything seems to have worked out fine.  Kyle wanted me to throw it in here anyways.  

![screen shot 2015-05-23 at 9 24 20 am](https://cloud.githubusercontent.com/assets/8727476/7784561/a988f7aa-012f-11e5-92b1-2ecd84775564.png)

**Comment by joelworsham** [comment]
No longer present in 2.0
