### ISSUE TITLE
Help admins who can't get back to CD menu settings

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#110]
Currently, if an administrator changes the admin menu for their role, and happens to remove the link(s) to CD settings, they have no clear way to get back to it. We should come up with some solution for helping admins out of this predicament.

Props @Jy86422000

**Comment by joelworsham** [comment]
It should be impossible to remove the "Client Dash" menu item for an administrator

**Comment by Jy86422000** [comment]
Just and update to this.  I just downloaded a fresh copy from the repository.  I put the Client Dash settings in a separate menu under a menu item that says "Development Only".  I now get a 404 error when trying to reach it.  Also tried putting it in as a custom link, but it won't take.  
<img width="464" alt="screen shot 2015-08-27 at 6 25 42 pm" src="https://cloud.githubusercontent.com/assets/8727476/9535643/249b4aec-4ce9-11e5-9376-7449cd9ae3e8.png">

**Comment by joelworsham** [comment]
No longer possible in 2.0
