### ISSUE TITLE
WP Admin menu display in strange way

### ISSUE THREAD

**Issue by signo** [realbigplugins/client-dash#111]
I added a menu for the editor role and it shows all wrong, all the menu links point to site_domain/wp-admin, i tested deactivating all plugins except client-dash and still got the strange behavior, if i delete the custom menu in client dash the admin menu works as usual. My setup is WP Multi Site 4.2.2, i did try with the plugin "network activated" and "site activated". please see the attached image.

http://postimg.org/image/blp31oc9p/

**Comment by joelworsham** [comment]
I'm sorry to hear this! We will look into this shortly.

**Comment by signo** [comment]
Hi, while you figure out this bug, would you have a temp fix? some hack in the code or maybe erasing all options for the plugin to start over? Otherwise i need to look for an alternative plugin but i really like client dash's approach.

**Comment by joelworsham** [comment]
No longer present in 2.0
