### ISSUE TITLE
Add new tabs to Webmaster page

### ISSUE THREAD

**Issue by joelworsham** [realbigplugins/client-dash#114]
From Client Dash settings.

**Comment by brashrebel** [comment]
I'm not sure what this issue is. Can you explain?

**Comment by joelworsham** [comment]
Adding more tabs to the Webmaster page, preferably from the Webmaster Settings page. It's been requested in various issues and we typically recommend creating an extension to do it.

**Comment by brashrebel** [comment]
So like, some UI in the settings section for just dynamically creating new tabs with a WYSIWYG for putting content in them?

**Comment by joelworsham** [comment]
That's what I'm thinking. Basically the Webmaster tab, but the ability to create more

**Comment by BigActual** [comment]
and shortcodes

**Comment by joelworsham** [comment]
Done in CD pro now with admin pages
