### ISSUE TITLE
v2.0 deactivates itself on update

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#138]
The current version of Client Dash uses the file `init.php` as its main Plugin File, but v2.0 uses `client-dash.php`.

I do prefer the newer file name overall, but it deactivating itself could be confusing for users :/

Not sure if it would handle it properly during a _"real"_ update or not. It just happened to me switching Git Branches.

**Comment by d4mation** [comment]
We might be able to test this functionality using GitHub Updater. I'm not 100% certain that will fully replicate a "regular" Plugin Update though.

**Comment by joelworsham** [comment]
Using this repository is _not_ how the plugin is distributed on WordPress.org. So, init.php only applies to if you download this repository directly.

I regret building out the repository this way back in the day. I thought it would make development easier, but it just complicated things.

**Comment by d4mation** [comment]
Ah, I see. I figured this was ultimately a clone of Trac/What's on the .org Repo. My bad :+1:
