### ISSUE TITLE
Two left pointing arrows causes mucho confusion

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#146]
When working in the customizer thingy, there's a left pointing arrow on the top left which collapses the editor. There is also a left pointing arrow on the bottom left which takes the user back one step in the workflow. When using it, I mistakenly hit the wrong arrow numerous times.

So a couple problems here:

1. I always encourage extreme caution when relying heavily on icons without text. They're often not as intuitive to more basic users as we'd like to believe. Looking at the actual WordPress frontend customizer you'll see a little less of this and it is a bit more clear. Also, it uses text next to the Hide Controls arrow.
2. The arrows mentioned in the description are also present in the WP frontend customizer but they are reversed. Hiding the controls is at the bottom and moving backwards in the flow is on top. Might be why I messed it up so many times.

**Comment by arnonzamir** [comment]
Double that. Causes some hassle.

**Comment by joelworsham** [comment]
Good call. I was wondering how those would go over.

I'm limited by space here so text always visible is out. I will experiment more with a way to add clarity here.

**Comment by joelworsham** [comment]
Give 'er a try now. I made some adjustments based on your feedback and I'd be interested to know your thoughts.

**Comment by d4mation** [comment]
I agree that it could be confusing how it was, but I'm wondering if the placement of buttons is more the cause of the confusion than the lack of text.

The now mixture of Full Text along the top with Icons along the bottom now seems odd as well.

Client Dash Customizer, Hide is at the Top:
![image](https://user-images.githubusercontent.com/7770631/30926431-1f4c657e-a383-11e7-9a75-82a91cbb2620.png)

WordPress Customizer, Hide is at the Bottom:
![image](https://user-images.githubusercontent.com/7770631/30926341-ccd53924-a382-11e7-8a5d-9788a516c1bd.png)

The fact that the "Hide" button for the Client Dash Customizer is at the top is even more confusing when you consider the "Restore" button is at the _bottom_ of the screen:

![image](https://user-images.githubusercontent.com/7770631/30926410-0b8ce57c-a383-11e7-8af2-77d3e8f78399.png)

**Comment by joelworsham** [comment]
Not bad points. I don't want to compare with the WP Customizer too much. I do understand that the people using the CD Customizer will most likely be familiar with WP Customizer, so I understand the concern, but I also do want to make choices that are truly best for the CD Customizer.

I'm definitely open to suggestions because I'm a bit at a loss for how else to arrange things. It seems to make a lot of sense for "Panel Actions" to the be at the bottom and "Primary Actions" to be at the top. Perhaps hiding the customizer isn't considered a "Primary Action" and should be placed elsewhere? If so, I'm not entirely sure where that would be. I suppose maybe it could simply exist where the restore button is? So it looks the same, but with an opposite facing arrow? Just spitballing here.

**Comment by brashrebel** [comment]
I definitely expected the hide panel button to be at the bottom and go back to be at the top. That's not just the customizer. The back button is top left in browsers and even in WordPress the collapse admin menu option is at the bottom of the menu. I think back should be top, hide should be bottom.

Besides that, nice changes!

**Comment by joelworsham** [comment]
I'll probably leave the placement as is. I understand some other systems do this, but I've also seen systems that do similar to my layout, and I do believe it is intuitive. I would prefer to keep "Primary" actions at the top and "Secondary" actions at the bottom.

But I do think the changes made were beneficial and I appreciate the input!

**Comment by joelworsham** [comment]
@brashrebel I lied. I changed a bunch of stuff around. I think you'll like. Take a look!
