### ISSUE TITLE
Might be possible to make editing a submenu more intuitive

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#148]
Been playing with it for a while and am debating whether it would be better to remove the current icon/link for each top level menu item to edit its submenu and instead just put a text link _inside_ the expanded options for that menu item. For that matter, moving the delete option inside _might_ even be a good idea too. That's what the WP frontend customizer does. That way every menu item shows only the title and the down arrow toggle icon with all options nested inside.

This is entirely open for discussion but the more I think about it, the more I like it. I'm a pretty quick learner with these things and have even used this interface before and I still had to think a little and click around before it all became clear. This gives me pause and makes me wonder whether we shouldn't adjust to include more text in conjunction with icons in general AND reduce the number of "icon groups" found throughout the interface. An isolated icon like an "x" or an arrow can be pretty obvious but a row of icons tends to greatly increase the cognitive load.

Again, open to discussion but hoping to make this easier to use.

**Comment by joelworsham** [comment]
I'm open to moving the control buttons for line-items (widgets and menu items) into the drop-down.

As for "reducing the number of icon groups", I really don't understand how this would happen. I can't remove controls, they are all necessary. We'd simply need to adjust location/icon/text and whatnot. But I think this conversation should continue in the other thread perhaps.

**Comment by joelworsham** [comment]
Give 'er a try now.
