### ISSUE TITLE
Client Dash Admin Menus show within the WordPress Customizer for Frontend Menus and under Appearance->Menus

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#149]
I figure this is unintentional. Not sure if I ever noticed this before testing v2.0.

![image](https://user-images.githubusercontent.com/7770631/30926591-a566e634-a383-11e7-8789-0b9f6d274f4b.png)

![image](https://user-images.githubusercontent.com/7770631/30926619-be4bc520-a383-11e7-81b1-e0dc2b43d9df.png)

**Comment by d4mation** [comment]
It is also possible this is not a problem any more and is the result of old code. I'd need to test on a clean install to be sure.

**Comment by joelworsham** [comment]
This is from < 2.0. The upgrade process should delete those old menus.

**Comment by d4mation** [comment]
Yep, just checked on a clean install and just confirmed it is pre v2.0.

I'm going to clean it out again and run through a fresh upgrade to see if they remove themselves.

**Comment by d4mation** [comment]
Confirmed fixed. Guessing that may not have been part of the migration when I last tested it. Closing.

**Comment by joelworsham** [comment]
Correct. The first time I pushed the upgrade process for testing, I removed the deleting functionality so it would be easier to continually test it.
