### ISSUE TITLE
Check if a User Role has the ability to view a Page before allowing it to be added to their Menu

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#150]
I'm not sure how feasible this is, but this would be a neat feature. That HelpScout ticket made me think of this.

If a Menu Item that contains a link to a page within the site were to be added, it would be cool if in the background Client Dash ran some kind of check to see if that User Role can view that page or not. If they can't, maybe alert the user saying which Capability they lack?

**Comment by d4mation** [comment]
Actually, it looks like (At least in v1.6.X) you've got something along these lines already. The bug is caused by something else entirely.

I'll get working on a PR. I've gotten one piece of the puzzle working, but there's probably one more still to go. I don't know how to release to the WP Repo, so that part would have to wait until next week when you're back 🤐

**Comment by joelworsham** [comment]
Also, it should be impossible for a user to add a menu-item that a user role cannot view. Especially in 2.0, because the available items are populated only by what the user role can see, and nothing else.
