### ISSUE TITLE
Huge wall of errors on Upgrade/Migrate

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#157]
Settings Migrated:

1. I changed the name of the "Dashboard" Menu Item for the Administrator Role
2. I changed the Icon for "Account" under "Icons"
3. Added some text under the "Webmaster" tab in the "Content" field

> Notice: Undefined offset: 5 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 159
> 
> Notice: Undefined offset: 6 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 160
> 
> Notice: Undefined offset: 5 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 159
> 
> Notice: Undefined offset: 6 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 160
> 
> Notice: Undefined offset: 5 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 159
> 
> Notice: Undefined offset: 6 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 160
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined offset: 3 in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 259
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 268
> 
> Notice: Undefined index: clientdash in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 236
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/clientdash-functions.php on line 101
> 
> Notice: Undefined index: clientdash in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 236
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/clientdash-functions.php on line 101
> 
> Notice: Undefined index: clientdash in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 236
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/clientdash-functions.php on line 101
> 
> Notice: Undefined index: clientdash in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 236
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/clientdash-functions.php on line 101
> 
> Notice: Undefined index: clientdash in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 236
> 
> Warning: Invalid argument supplied for foreach() in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/clientdash-functions.php on line 101
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:268) in /srv/www/clientdash/public_html/wp-admin/includes/misc.php on line 1114
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:268) in /srv/www/clientdash/public_html/wp-includes/option.php on line 919
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:268) in /srv/www/clientdash/public_html/wp-includes/option.php on line 920

**Comment by joelworsham** [comment]
I added many more checks to this part. Please let me know if the errors go away. Also, let me know if you notice any oddities after migration in the menu itself. Anything that jumps out at you as, "Oh, didn't expect that".

**Comment by d4mation** [comment]
Pulled latest changes to `2.0` branch and I've still got errors. Tried on a fresh WP install with the same setup as above and got the following:

> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Notice: Undefined index: type in /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php on line 282
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:282) in /srv/www/clientdash/public_html/wp-admin/includes/misc.php on line 1114
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:282) in /srv/www/clientdash/public_html/wp-includes/option.php on line 919
> 
> Warning: Cannot modify header information - headers already sent by (output started at /srv/www/clientdash/public_html/wp-content/plugins/client-dash/core/class-clientdash-modify.php:282) in /srv/www/clientdash/public_html/wp-includes/option.php on line 920

**Comment by d4mation** [comment]
All good now :+1:
