### ISSUE TITLE
Somehow make build script for publishing to SVN

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#170]
Right now publishing to SVN is manual and a massive chore. Automating this would be way better.

**Comment by d4mation** [comment]
Made a little Gulp Task to handle this. Expects the SVN Repo at `./client-dash-svn` inside the Git Repo.

**Comment by brashrebel** [comment]
Something like this? https://github.com/stephenharris/grunt-wp-deploy

**Comment by d4mation** [comment]
Hmm, that is close to what we would have needed, but not quite. 

Client Dash's release build on the SVN removes a bunch of dev-only files and runs the `gulp build --production` task to uglify the JS and such. 

That Grunt Task seems to only Check In changes once they are in a build/release directory already and runs some checks on things like Version Numbers matching in the Plugin File and `readme.txt`. 

I don't really mind running `svn ci -m 'Checking in Trunk'` `svn cp trunk/ tags/<version>` `svn ci 'Tagging <version>`. It was getting all the correct files into the Trunk directory that was a pain as copying only the correct files was all manual. Now I don't have to worry about that for future releases 👍

**Comment by d4mation** [comment]
As a note for future me:

If you need to bump just "Tested To" in the `readme.txt`, you can copy just that file to the _most recent Tag_ in SVN and then Check In that change.
