### ISSUE TITLE
Incompatibility with Wishlist Member

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/client-dash#185]
When Wishlist Member is active, it apparently prevents the Customizer from working at all. 

This is likely some kind of priority issue or similar. As it is a premium plugin, accounting for this may be difficult unless we're able to get a test license from them.

https://member.wishlistproducts.com/

https://secure.helpscout.net/conversation/1202182337/3568?folderId=955392

**Comment by d4mation** [comment]
https://github.com/realbigplugins/client-dash/commit/0411aaeab6e28b38fcf1c25bf4d51e739a15ae29

**Comment by joelyoder** [comment]
Closing this issue since the fix was merged.
