### ISSUE TITLE
More server info on Help- >Info

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#23]
There isn't much information on this page. I'd like to make it more useful. Can we incorporate information like:

Current PHP version
Server OS
Memory limit
Site IP address
User's browser
User's OS
etc.

**Comment by joelworsham** [comment]
bump, easy add

**Comment by joelyoder** [comment]
@d4mation since this info is either present on the Site Health dashboard or easy to find elsewhere, do we even need the Info tab anymore?

**Comment by d4mation** [comment]
We're requiring WP 4.8 now as a minimum, right? When was it added to WP? If it was added before 4.8 I'd say we definitely don't need an integrated Server Info page within the plugin.

**Comment by joelyoder** [comment]
Health check is a 5.2 thing. So there would be some users that do not have that panel, although only ~10% of the install base is <5.2 at this point: https://wordpress.org/about/stats/

**Comment by d4mation** [comment]
I wouldn't worry about it then, personally. At that point, during troubleshooting we would be recommending that they update all plugins/themes and core to latest anyhow. Closing.
