### ISSUE TITLE
Options for WordPress news widget

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#63]
The WordPress news widget could use some options to make it so much more awesome:
- Add more RSS feeds
- Remove existing feeds
- Show/hide excerpt

Any of these would make it viable. All of them would make it awesome.

**Comment by joelworsham** [comment]
Include this in #167

**Comment by d4mation** [comment]
I believe I found the Filter mentioned here, but it seems to only allow you to change the existing RSS Feeds rather than to add/remove any or to change their settings.

https://github.com/WordPress/WordPress/blob/da7a80d67fea29c2badfc538bfc01c8a585f0cbe/wp-admin/includes/dashboard.php#L1316-L1401
