### ISSUE TITLE
Export/Import CD settings

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#79]
We're getting to have a lot of settings by now. It would be amazing to offer an export/import feature where webmasters could export their settings including display, menus, icons, webmaster, widgets, etc.

**Comment by joelworsham** [comment]
This is HUGE. People want this so bad.

I think it's a pro option personally. Let's DO IT.

**Comment by d4mation** [comment]
Turns out I made a duplicate of this in #159, but there's more details there so I'm going to close this one in favor of it. Sorry 🤐
