### ISSUE TITLE
Live chat extension

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/client-dash#96]
I would absolutely love to create an extension which brings live chat capabilities into the WP dashboard so that logged in users can communicate directly. I could see a lot of people finding this useful, especially if it were built well and easy to use. Here's a couple concepts:
![chat-widget](https://cloud.githubusercontent.com/assets/4993131/4720669/b3cb3a20-5932-11e4-9a27-847baf526483.png)
![chat](https://cloud.githubusercontent.com/assets/4993131/4720668/b3c45534-5932-11e4-92de-18d64c16b8a9.png)

One is a mockup of the Chat tab on the Help page and the other is a dashboard widget which could be created and made available as well.

**Comment by joelworsham** [comment]
I don't think this should be a CD thing. Sounds like a standalone solution.
