### ISSUE TITLE
Hide WordPress Elements

### ISSUE THREAD

**Issue by fpcorso** [realbigplugins/client-dash#99]
Hey guys. First, I really like what you have done so far. Great job.

The plugin does a great job of assisting in setting up my client's dashboard. However, there are a few elements left that I have to keep changing with my own small custom plugin that would be very useful in this plugin.

First, being able to change/hide the footer text (i.e. "Thank you for creating with WordPress." and version #) would be a great addition to the plugin.

Second, some of my clients have sites that do not use comments so getting rid of the comments icon next to the site name at the top is useful.

Third, some clients sites do not need the +New menu at all. This too would be useful to be able to get rid of.

Finally, the "Howdy, _____" menu. I have to change the Howdy text and rename/remove the Edit Your Profile on almost every installation. That would be a great addition for this plugin.

Right now, I have a custom plugin that does most of this that I wrote, but it would be useful to have these built into this plugin. I wasn't sure if you would want these in separate issues or in just the one.

Thanks for the great plugin. Keep up the good work!

**Comment by joelworsham** [comment]
Probably eventually will become part of a bigger, overaching design interface in the pro version.
